// Generated by scripts/fetch-demo-tracklists.mjs from MusicBrainz — do not edit by hand;
// change DEMO_ALBUM_PICKS in demoAlbumPicks.mjs and re-run the script.
export const DEMO_ALBUMS = [
  {
    "artist": "Miles Davis",
    "title": "Kind of Blue",
    "tags": [
      "Jazz"
    ],
    "mood": "minor",
    "bpm": 72,
    "format": "flac",
    "year": 1959,
    "tracks": [
      {
        "title": "So What",
        "durationSecs": 545
      },
      {
        "title": "Freddie Freeloader",
        "durationSecs": 576
      },
      {
        "title": "Blue in Green",
        "durationSecs": 329
      },
      {
        "title": "All Blues",
        "durationSecs": 694
      },
      {
        "title": "Flamenco Sketches",
        "durationSecs": 565
      }
    ]
  },
  {
    "artist": "John Coltrane",
    "title": "A Love Supreme",
    "tags": [
      "Jazz"
    ],
    "mood": "minor",
    "bpm": 80,
    "format": "flac",
    "year": 1965,
    "tracks": [
      {
        "title": "A Love Supreme, Part 1: Acknowledgement",
        "durationSecs": 467
      },
      {
        "title": "A Love Supreme, Part 2: Resolution",
        "durationSecs": 447
      },
      {
        "title": "A Love Supreme, Part 3: Pursuance / A Love Supreme, Part 4: Psalm",
        "durationSecs": 1073
      }
    ]
  },
  {
    "artist": "The Beatles",
    "title": "Abbey Road",
    "tags": [
      "Rock",
      "Pop"
    ],
    "mood": "major",
    "bpm": 112,
    "year": 1969,
    "tracks": [
      {
        "title": "Come Together",
        "durationSecs": 260
      },
      {
        "title": "Something",
        "durationSecs": 182
      },
      {
        "title": "Maxwell's Silver Hammer",
        "durationSecs": 208
      },
      {
        "title": "Oh! Darling",
        "durationSecs": 207
      },
      {
        "title": "Octopus's Garden",
        "durationSecs": 171
      },
      {
        "title": "I Want You (She's So Heavy)",
        "durationSecs": 466
      },
      {
        "title": "Here Comes the Sun",
        "durationSecs": 185
      },
      {
        "title": "Because",
        "durationSecs": 166
      },
      {
        "title": "You Never Give Me Your Money",
        "durationSecs": 237
      },
      {
        "title": "Sun King",
        "durationSecs": 151
      },
      {
        "title": "Mean Mr. Mustard",
        "durationSecs": 66
      },
      {
        "title": "Polythene Pam",
        "durationSecs": 78
      },
      {
        "title": "She Came In Through the Bathroom Window",
        "durationSecs": 113
      },
      {
        "title": "Golden Slumbers",
        "durationSecs": 91
      },
      {
        "title": "Carry That Weight",
        "durationSecs": 96
      },
      {
        "title": "The End",
        "durationSecs": 141
      },
      {
        "title": "Her Majesty",
        "durationSecs": 25
      }
    ]
  },
  {
    "artist": "The Beach Boys",
    "title": "Pet Sounds",
    "tags": [
      "Pop",
      "Rock"
    ],
    "mood": "major",
    "bpm": 104,
    "year": 1966,
    "tracks": [
      {
        "title": "Wouldn't It Be Nice",
        "durationSecs": 145
      },
      {
        "title": "You Still Believe in Me",
        "durationSecs": 151
      },
      {
        "title": "That's Not Me",
        "durationSecs": 148
      },
      {
        "title": "Don't Talk (Put Your Head on My Shoulder)",
        "durationSecs": 172
      },
      {
        "title": "I'm Waiting for the Day",
        "durationSecs": 185
      },
      {
        "title": "Let's Go Away for Awhile",
        "durationSecs": 138
      },
      {
        "title": "Sloop John B",
        "durationSecs": 178
      },
      {
        "title": "God Only Knows",
        "durationSecs": 171
      },
      {
        "title": "I Know There's an Answer",
        "durationSecs": 189
      },
      {
        "title": "Here Today",
        "durationSecs": 174
      },
      {
        "title": "I Just Wasn't Made for These Times",
        "durationSecs": 192
      },
      {
        "title": "Pet Sounds",
        "durationSecs": 142
      },
      {
        "title": "Caroline, No",
        "durationSecs": 169
      }
    ]
  },
  {
    "artist": "Pink Floyd",
    "title": "The Dark Side of the Moon",
    "tags": [
      "Rock",
      "Progressive Rock"
    ],
    "mood": "minor",
    "bpm": 76,
    "year": 1973,
    "tracks": [
      {
        "title": "Speak to Me",
        "durationSecs": 73
      },
      {
        "title": "Breathe",
        "durationSecs": 166
      },
      {
        "title": "On the Run",
        "durationSecs": 215
      },
      {
        "title": "Time",
        "durationSecs": 424
      },
      {
        "title": "The Great Gig in the Sky",
        "durationSecs": 288
      },
      {
        "title": "Money",
        "durationSecs": 383
      },
      {
        "title": "Us and Them",
        "durationSecs": 470
      },
      {
        "title": "Any Colour You Like",
        "durationSecs": 205
      },
      {
        "title": "Brain Damage",
        "durationSecs": 230
      },
      {
        "title": "Eclipse",
        "durationSecs": 124
      }
    ]
  },
  {
    "artist": "Fleetwood Mac",
    "title": "Rumours",
    "tags": [
      "Rock",
      "Pop"
    ],
    "mood": "major",
    "bpm": 118,
    "year": 1977,
    "tracks": [
      {
        "title": "Second Hand News",
        "durationSecs": 174
      },
      {
        "title": "Dreams",
        "durationSecs": 258
      },
      {
        "title": "Never Going Back Again",
        "durationSecs": 135
      },
      {
        "title": "Don't Stop",
        "durationSecs": 194
      },
      {
        "title": "Go Your Own Way",
        "durationSecs": 220
      },
      {
        "title": "Songbird",
        "durationSecs": 203
      },
      {
        "title": "The Chain",
        "durationSecs": 271
      },
      {
        "title": "You Make Loving Fun",
        "durationSecs": 213
      },
      {
        "title": "I Don't Want to Know",
        "durationSecs": 195
      },
      {
        "title": "Oh Daddy",
        "durationSecs": 238
      },
      {
        "title": "Gold Dust Woman",
        "durationSecs": 302
      }
    ]
  },
  {
    "artist": "Stevie Wonder",
    "title": "Songs in the Key of Life",
    "tags": [
      "Pop",
      "Soul"
    ],
    "mood": "major",
    "bpm": 100,
    "year": 1976,
    "tracks": [
      {
        "title": "Love's in Need of Love Today",
        "durationSecs": 426
      },
      {
        "title": "Have a Talk With God",
        "durationSecs": 162
      },
      {
        "title": "Village Ghetto Land",
        "durationSecs": 205
      },
      {
        "title": "Contusion",
        "durationSecs": 226
      },
      {
        "title": "Sir Duke",
        "durationSecs": 234
      },
      {
        "title": "I Wish",
        "durationSecs": 252
      },
      {
        "title": "Knocks Me Off My Feet",
        "durationSecs": 216
      },
      {
        "title": "Pastime Paradise",
        "durationSecs": 208
      },
      {
        "title": "Summer Soft",
        "durationSecs": 254
      },
      {
        "title": "Ordinary Pain",
        "durationSecs": 383
      },
      {
        "title": "Isn't She Lovely",
        "durationSecs": 395
      },
      {
        "title": "Joy Inside My Tears",
        "durationSecs": 390
      },
      {
        "title": "Black Man",
        "durationSecs": 510
      },
      {
        "title": "Ngiculela - Es una historia - I Am Singing",
        "durationSecs": 229
      },
      {
        "title": "If It's Magic",
        "durationSecs": 192
      },
      {
        "title": "As",
        "durationSecs": 428
      },
      {
        "title": "Another Star",
        "durationSecs": 508
      },
      {
        "title": "Saturn",
        "durationSecs": 294
      },
      {
        "title": "Ebony Eyes",
        "durationSecs": 249
      },
      {
        "title": "All Day Sucker",
        "durationSecs": 306
      },
      {
        "title": "Easy Goin' Evening (My Mama's Call)",
        "durationSecs": 237
      }
    ]
  },
  {
    "artist": "Michael Jackson",
    "title": "Thriller",
    "tags": [
      "Pop",
      "Funk"
    ],
    "mood": "minor",
    "bpm": 118,
    "year": 1982,
    "tracks": [
      {
        "title": "Wanna Be Startin' Somethin'",
        "durationSecs": 363
      },
      {
        "title": "Baby Be Mine",
        "durationSecs": 261
      },
      {
        "title": "The Girl Is Mine",
        "durationSecs": 222
      },
      {
        "title": "Thriller",
        "durationSecs": 360
      },
      {
        "title": "Beat It",
        "durationSecs": 259
      },
      {
        "title": "Billie Jean",
        "durationSecs": 294
      },
      {
        "title": "Human Nature",
        "durationSecs": 246
      },
      {
        "title": "P.Y.T. (Pretty Young Thing)",
        "durationSecs": 239
      },
      {
        "title": "The Lady in My Life",
        "durationSecs": 299
      }
    ]
  },
  {
    "artist": "U2",
    "title": "The Joshua Tree",
    "tags": [
      "Rock"
    ],
    "mood": "major",
    "bpm": 108,
    "year": 1987,
    "tracks": [
      {
        "title": "Where the Streets Have No Name",
        "durationSecs": 337
      },
      {
        "title": "I Still Haven't Found What I'm Looking For",
        "durationSecs": 279
      },
      {
        "title": "With or Without You",
        "durationSecs": 296
      },
      {
        "title": "Bullet the Blue Sky",
        "durationSecs": 272
      },
      {
        "title": "Running to Stand Still",
        "durationSecs": 259
      },
      {
        "title": "Red Hill Mining Town",
        "durationSecs": 294
      },
      {
        "title": "In God's Country",
        "durationSecs": 177
      },
      {
        "title": "Trip Through Your Wires",
        "durationSecs": 212
      },
      {
        "title": "One Tree Hill",
        "durationSecs": 283
      },
      {
        "title": "Exit",
        "durationSecs": 293
      },
      {
        "title": "Mothers of the Disappeared",
        "durationSecs": 311
      }
    ]
  },
  {
    "artist": "Prince",
    "title": "Purple Rain",
    "tags": [
      "Pop",
      "Funk"
    ],
    "mood": "minor",
    "bpm": 112,
    "year": 1984,
    "tracks": [
      {
        "title": "Let's Go Crazy",
        "durationSecs": 280
      },
      {
        "title": "Take Me With U",
        "durationSecs": 234
      },
      {
        "title": "The Beautiful Ones",
        "durationSecs": 314
      },
      {
        "title": "Computer Blue",
        "durationSecs": 239
      },
      {
        "title": "Darling Nikki",
        "durationSecs": 255
      },
      {
        "title": "When Doves Cry",
        "durationSecs": 354
      },
      {
        "title": "I Would Die 4 U",
        "durationSecs": 169
      },
      {
        "title": "Baby I'm a Star",
        "durationSecs": 265
      },
      {
        "title": "Purple Rain",
        "durationSecs": 521
      }
    ]
  },
  {
    "artist": "Nirvana",
    "title": "Nevermind",
    "tags": [
      "Rock",
      "Grunge"
    ],
    "mood": "minor",
    "bpm": 124,
    "year": 1991,
    "tracks": [
      {
        "title": "Smells Like Teen Spirit",
        "durationSecs": 301
      },
      {
        "title": "In Bloom",
        "durationSecs": 255
      },
      {
        "title": "Come as You Are",
        "durationSecs": 219
      },
      {
        "title": "Breed",
        "durationSecs": 184
      },
      {
        "title": "Lithium",
        "durationSecs": 257
      },
      {
        "title": "Polly",
        "durationSecs": 177
      },
      {
        "title": "Territorial Pissings",
        "durationSecs": 143
      },
      {
        "title": "Drain You",
        "durationSecs": 224
      },
      {
        "title": "Lounge Act",
        "durationSecs": 157
      },
      {
        "title": "Stay Away",
        "durationSecs": 212
      },
      {
        "title": "On a Plain",
        "durationSecs": 196
      },
      {
        "title": "Something in the Way / Endless, Nameless",
        "durationSecs": 1235
      }
    ]
  },
  {
    "artist": "Radiohead",
    "title": "OK Computer",
    "tags": [
      "Rock",
      "Alternative"
    ],
    "mood": "minor",
    "bpm": 88,
    "year": 1997,
    "tracks": [
      {
        "title": "Airbag",
        "durationSecs": 284
      },
      {
        "title": "Paranoid Android",
        "durationSecs": 383
      },
      {
        "title": "Subterranean Homesick Alien",
        "durationSecs": 268
      },
      {
        "title": "Exit Music (for a Film)",
        "durationSecs": 265
      },
      {
        "title": "Let Down",
        "durationSecs": 299
      },
      {
        "title": "Karma Police",
        "durationSecs": 262
      },
      {
        "title": "Fitter Happier",
        "durationSecs": 117
      },
      {
        "title": "Electioneering",
        "durationSecs": 231
      },
      {
        "title": "Climbing Up the Walls",
        "durationSecs": 285
      },
      {
        "title": "No Surprises",
        "durationSecs": 229
      },
      {
        "title": "Lucky",
        "durationSecs": 260
      },
      {
        "title": "The Tourist",
        "durationSecs": 325
      }
    ]
  },
  {
    "artist": "Massive Attack",
    "title": "Mezzanine",
    "tags": [
      "Electronic",
      "Trip Hop"
    ],
    "mood": "minor",
    "bpm": 80,
    "year": 1998,
    "tracks": [
      {
        "title": "Angel",
        "durationSecs": 381
      },
      {
        "title": "Risingson",
        "durationSecs": 299
      },
      {
        "title": "Teardrop",
        "durationSecs": 331
      },
      {
        "title": "Inertia Creeps",
        "durationSecs": 357
      },
      {
        "title": "Exchange",
        "durationSecs": 251
      },
      {
        "title": "Dissolved Girl",
        "durationSecs": 367
      },
      {
        "title": "Man Next Door",
        "durationSecs": 356
      },
      {
        "title": "Black Milk",
        "durationSecs": 382
      },
      {
        "title": "Mezzanine",
        "durationSecs": 357
      },
      {
        "title": "Group Four",
        "durationSecs": 492
      },
      {
        "title": "(Exchange)",
        "durationSecs": 250
      }
    ]
  },
  {
    "artist": "Radiohead",
    "title": "Kid A",
    "tags": [
      "Rock",
      "Electronic"
    ],
    "mood": "minor",
    "bpm": 84,
    "year": 2000,
    "tracks": [
      {
        "title": "Everything in Its Right Place",
        "durationSecs": 251
      },
      {
        "title": "Kid A",
        "durationSecs": 285
      },
      {
        "title": "The National Anthem",
        "durationSecs": 352
      },
      {
        "title": "How to Disappear Completely",
        "durationSecs": 356
      },
      {
        "title": "Treefingers",
        "durationSecs": 223
      },
      {
        "title": "Optimistic",
        "durationSecs": 316
      },
      {
        "title": "In Limbo",
        "durationSecs": 211
      },
      {
        "title": "Idioteque",
        "durationSecs": 309
      },
      {
        "title": "Morning Bell",
        "durationSecs": 276
      },
      {
        "title": "Motion Picture Soundtrack",
        "durationSecs": 419
      }
    ]
  },
  {
    "artist": "The Strokes",
    "title": "Is This It",
    "tags": [
      "Rock",
      "Indie"
    ],
    "mood": "major",
    "bpm": 140,
    "year": 2001,
    "tracks": [
      {
        "title": "Is This It",
        "durationSecs": 154
      },
      {
        "title": "The Modern Age",
        "durationSecs": 213
      },
      {
        "title": "Soma",
        "durationSecs": 158
      },
      {
        "title": "Barely Legal",
        "durationSecs": 238
      },
      {
        "title": "Someday",
        "durationSecs": 187
      },
      {
        "title": "Alone, Together",
        "durationSecs": 192
      },
      {
        "title": "Last Nite",
        "durationSecs": 198
      },
      {
        "title": "Hard to Explain",
        "durationSecs": 228
      },
      {
        "title": "New York City Cops",
        "durationSecs": 216
      },
      {
        "title": "Trying Your Luck",
        "durationSecs": 208
      },
      {
        "title": "Take It or Leave It",
        "durationSecs": 196
      }
    ]
  },
  {
    "artist": "Arcade Fire",
    "title": "Funeral",
    "tags": [
      "Rock",
      "Indie"
    ],
    "mood": "major",
    "bpm": 120,
    "year": 2004,
    "tracks": [
      {
        "title": "Neighborhood #1 (Tunnels)",
        "durationSecs": 288
      },
      {
        "title": "Neighborhood #2 (Laïka)",
        "durationSecs": 212
      },
      {
        "title": "Une année sans lumière",
        "durationSecs": 221
      },
      {
        "title": "Neighborhood #3 (Power Out)",
        "durationSecs": 313
      },
      {
        "title": "Neighborhood #4 (7 Kettles)",
        "durationSecs": 290
      },
      {
        "title": "Crown of Love",
        "durationSecs": 282
      },
      {
        "title": "Wake Up",
        "durationSecs": 335
      },
      {
        "title": "Haïti",
        "durationSecs": 247
      },
      {
        "title": "Rebellion (Lies)",
        "durationSecs": 311
      },
      {
        "title": "In the Backseat",
        "durationSecs": 380
      }
    ]
  },
  {
    "artist": "Daft Punk",
    "title": "Random Access Memories",
    "tags": [
      "Electronic",
      "Disco"
    ],
    "mood": "major",
    "bpm": 112,
    "year": 2013,
    "tracks": [
      {
        "title": "Give Life Back to Music",
        "durationSecs": 274
      },
      {
        "title": "The Game of Love",
        "durationSecs": 321
      },
      {
        "title": "Giorgio by Moroder",
        "durationSecs": 544
      },
      {
        "title": "Within",
        "durationSecs": 228
      },
      {
        "title": "Instant Crush",
        "durationSecs": 337
      },
      {
        "title": "Lose Yourself to Dance",
        "durationSecs": 353
      },
      {
        "title": "Touch",
        "durationSecs": 498
      },
      {
        "title": "Get Lucky",
        "durationSecs": 367
      },
      {
        "title": "Beyond",
        "durationSecs": 290
      },
      {
        "title": "Motherboard",
        "durationSecs": 341
      },
      {
        "title": "Fragments of Time",
        "durationSecs": 279
      },
      {
        "title": "Doin' It Right",
        "durationSecs": 251
      },
      {
        "title": "Contact",
        "durationSecs": 381
      }
    ]
  },
  {
    "artist": "Kendrick Lamar",
    "title": "To Pimp a Butterfly",
    "tags": [
      "Hip Hop"
    ],
    "mood": "minor",
    "bpm": 92,
    "year": 2015,
    "tracks": [
      {
        "title": "Wesley's Theory",
        "durationSecs": 287
      },
      {
        "title": "For Free? (interlude)",
        "durationSecs": 131
      },
      {
        "title": "King Kunta",
        "durationSecs": 235
      },
      {
        "title": "Institutionalized",
        "durationSecs": 272
      },
      {
        "title": "These Walls",
        "durationSecs": 301
      },
      {
        "title": "u",
        "durationSecs": 268
      },
      {
        "title": "Alright",
        "durationSecs": 219
      },
      {
        "title": "For Sale? (interlude)",
        "durationSecs": 292
      },
      {
        "title": "Momma",
        "durationSecs": 283
      },
      {
        "title": "Hood Politics",
        "durationSecs": 293
      },
      {
        "title": "How Much a Dollar Cost",
        "durationSecs": 262
      },
      {
        "title": "Complexion (A Zulu Love)",
        "durationSecs": 263
      },
      {
        "title": "The Blacker the Berry",
        "durationSecs": 329
      },
      {
        "title": "You Ain't Gotta Lie (Momma Said)",
        "durationSecs": 242
      },
      {
        "title": "i",
        "durationSecs": 336
      },
      {
        "title": "Mortal Man",
        "durationSecs": 727
      }
    ]
  },
  {
    "artist": "Tame Impala",
    "title": "Currents",
    "tags": [
      "Rock",
      "Psychedelic"
    ],
    "mood": "major",
    "bpm": 106,
    "year": 2015,
    "tracks": [
      {
        "title": "Let It Happen",
        "durationSecs": 466
      },
      {
        "title": "Nangs",
        "durationSecs": 107
      },
      {
        "title": "The Moment",
        "durationSecs": 255
      },
      {
        "title": "Yes I'm Changing",
        "durationSecs": 270
      },
      {
        "title": "Eventually",
        "durationSecs": 319
      },
      {
        "title": "Gossip",
        "durationSecs": 55
      },
      {
        "title": "The Less I Know the Better",
        "durationSecs": 218
      },
      {
        "title": "Past Life",
        "durationSecs": 227
      },
      {
        "title": "Disciples",
        "durationSecs": 108
      },
      {
        "title": "'Cause I'm a Man",
        "durationSecs": 241
      },
      {
        "title": "Reality in Motion",
        "durationSecs": 252
      },
      {
        "title": "Love/Paranoia",
        "durationSecs": 186
      },
      {
        "title": "New Person, Same Old Mistakes",
        "durationSecs": 362
      }
    ]
  },
  {
    "artist": "Dua Lipa",
    "title": "Future Nostalgia",
    "tags": [
      "Pop",
      "Disco"
    ],
    "mood": "minor",
    "bpm": 120,
    "year": 2020,
    "tracks": [
      {
        "title": "Future Nostalgia",
        "durationSecs": 185
      },
      {
        "title": "Don't Start Now",
        "durationSecs": 183
      },
      {
        "title": "Cool",
        "durationSecs": 210
      },
      {
        "title": "Physical",
        "durationSecs": 195
      },
      {
        "title": "Levitating",
        "durationSecs": 204
      },
      {
        "title": "Pretty Please",
        "durationSecs": 195
      },
      {
        "title": "Hallucinate",
        "durationSecs": 209
      },
      {
        "title": "Love Again",
        "durationSecs": 258
      },
      {
        "title": "Break My Heart",
        "durationSecs": 222
      },
      {
        "title": "Good in Bed",
        "durationSecs": 219
      },
      {
        "title": "Boys Will Be Boys",
        "durationSecs": 166
      }
    ]
  },
  {
    "artist": "SZA",
    "title": "SOS",
    "tags": [
      "Hip Hop",
      "R&B"
    ],
    "mood": "minor",
    "bpm": 90,
    "year": 2022,
    "tracks": [
      {
        "title": "SOS",
        "durationSecs": 118
      },
      {
        "title": "Kill Bill",
        "durationSecs": 154
      },
      {
        "title": "Seek & Destroy",
        "durationSecs": 204
      },
      {
        "title": "Low",
        "durationSecs": 181
      },
      {
        "title": "Love Language",
        "durationSecs": 184
      },
      {
        "title": "Blind",
        "durationSecs": 151
      },
      {
        "title": "Used",
        "durationSecs": 147
      },
      {
        "title": "Snooze",
        "durationSecs": 202
      },
      {
        "title": "Notice Me",
        "durationSecs": 161
      },
      {
        "title": "Gone Girl",
        "durationSecs": 244
      },
      {
        "title": "Smoking on My Ex Pack",
        "durationSecs": 84
      },
      {
        "title": "Ghost in the Machine",
        "durationSecs": 219
      },
      {
        "title": "F2F",
        "durationSecs": 185
      },
      {
        "title": "Nobody Gets Me",
        "durationSecs": 181
      },
      {
        "title": "Conceited",
        "durationSecs": 151
      },
      {
        "title": "Special",
        "durationSecs": 159
      },
      {
        "title": "Too Late",
        "durationSecs": 164
      },
      {
        "title": "Far",
        "durationSecs": 181
      },
      {
        "title": "Shirt",
        "durationSecs": 182
      },
      {
        "title": "Open Arms",
        "durationSecs": 240
      },
      {
        "title": "I Hate U",
        "durationSecs": 174
      },
      {
        "title": "Good Days",
        "durationSecs": 278
      },
      {
        "title": "Forgiveless",
        "durationSecs": 142
      }
    ]
  },
  {
    "artist": "Alvvays",
    "title": "Blue Rev",
    "tags": [
      "Rock",
      "Indie"
    ],
    "mood": "major",
    "bpm": 132,
    "year": 2022,
    "tracks": [
      {
        "title": "Pharmacist",
        "durationSecs": 124
      },
      {
        "title": "Easy on Your Own?",
        "durationSecs": 175
      },
      {
        "title": "After the Earthquake",
        "durationSecs": 185
      },
      {
        "title": "Tom Verlaine",
        "durationSecs": 206
      },
      {
        "title": "Pressed",
        "durationSecs": 130
      },
      {
        "title": "Many Mirrors",
        "durationSecs": 179
      },
      {
        "title": "Very Online Guy",
        "durationSecs": 142
      },
      {
        "title": "Velveteen",
        "durationSecs": 190
      },
      {
        "title": "Tile by Tile",
        "durationSecs": 178
      },
      {
        "title": "Pomeranian Spinster",
        "durationSecs": 205
      },
      {
        "title": "Belinda Says",
        "durationSecs": 165
      },
      {
        "title": "Bored in Bristol",
        "durationSecs": 180
      },
      {
        "title": "Lottery Noises",
        "durationSecs": 198
      },
      {
        "title": "Fourth Figure",
        "durationSecs": 80
      }
    ]
  }
];
